name: verify_identity
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_ui_auth: ^1.16.1

  # Utils
  provider: ^6.1.5
  fluttertoast: ^8.2.12

  # Icons
  cupertino_icons: ^1.0.8

  # languages
  google_fonts: ^6.2.1

  # lang
  easy_localization: ^3.0.7+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

 # language
  assets:
    # language
    - assets/lang/

    # image
    - assets/image/img_profile.png



